### ISSUE TITLE
Unexpected expression in type/color.pat

### ISSUE THREAD

**Issue by Bosek** [WerWolv/ImHex-Patterns#103]
I am getting errors trying to `#include <type/colors.pat>`. So I tried to copy it's content directly into my pattern editor and got this error:
```
error[P0002]: Unexpected expression
  --> <Source Code>:19:14
19 |     bitfield RGBA<auto R, auto G, auto B, auto A> {
                  ^
                  Expected '{' after bitfield declaration, got Operator (<).
```  
I've read #102 and I suppose it should solve it. I just wanted to write the issue so nobody else have to dig through the code to figure it out like I did.

**Comment by WerWolv** [comment]
Thank you. Closing this now as the latest release of ImHex supports these features correctly
