### ISSUE TITLE
How to write a list of pointers (instead of a pointer to a list)

### ISSUE THREAD

**Issue by Fl0GUI** [WerWolv/ImHex-Patterns#104]
I'm trying to write a pattern for [doom's image format](https://doomwiki.org/wiki/Picture_format).
The header has a list of pointers. The length of this list is equal to the width of the image, which is defined in the header.
If I write:

`Post *post[width]: u32;`

I one pointer to a width amount of posts, instead of width amount of pointers to post.
The documentation doesn't mention how to do this and trial and error got me nowhere.

The complete pattern:
```Rust
struct Post {
    le s8 topDelta;
    le u8 length;
    padding[1];
    le u8 data[length];
    padding[1];
    le u8 end;
};

struct Lmp {
    le s16 width;
    le s16 height;
    le s16 leftOffset;
    le s16 topOffset;
    Post *post[width]: u32; // this is incorrect
};

Lmp lmp @ 0;
```

This does work for now, as most doom images have their posts in a continuous array.

**Comment by WerWolv** [comment]
Hey
Using this syntax you can only make a pointer to an array. If you instead want an array of pointers, you need to wrap your pointer into a new type and then create an array of that.

For example:
```cpp
struct Pointer<T> {
    T *pointer : u32;
};

struct Lmp {
    // ...
    Pointer<Post> post[width];
};
```

**Comment by Fl0GUI** [comment]
Hi,
That is indeed the answer. Thank you very much for your incredibly fast reply!
