### ISSUE TITLE
PE Pattern on 'libimhex.dll' keeps evaluating

### ISSUE THREAD

**Issue by learn-more** [WerWolv/ImHex-Patterns#109]
- ImHex v1.28.0 portable
- Win10 22H2

Reproduction:
- Opened `libimhex.dll`
- File -> Import -> Pattern File
- ImHex stays on 'Evaluating' the pattern

**Comment by WerWolv** [comment]
Hey
Depending on the size of the binary, the PE pattern can take a very long time. It's one of the most complicated patterns we have.
And libimhex.dll is really really big, especially with Debug symbols turned on. So it just takes a while to crunch through all the data
