### ISSUE TITLE
java pattern error[V0002]: Statement redefinition

### ISSUE THREAD

**Issue by Guigumua** [WerWolv/ImHex-Patterns#116]
ImHex: v1.29.0
```
error[V0002]: Statement redefinition
  --> <Source Code>:609:49
609 |         cp_ref name_index @ addressof(name_index);
                                                      ^
                                                      Redefinition of identifier 'name_index'


```
![image](https://github.com/WerWolv/ImHex-Patterns/assets/43509652/c17d2869-9a7a-4fa0-bc6b-cca432ab779b)

If delete line 609, 624, 653, pattern can be evaluated
![image](https://github.com/WerWolv/ImHex-Patterns/assets/43509652/e0e7bf42-a12f-4b66-be7b-c532f8b7c0b4)

**Comment by Nowilltolife** [comment]
The pattern was made in a version where defining 2 patterns with the same name was possible was possible. To adapt the pattern, simply rename the ones with the "hidden" attribute to _ and make the null if check reflect that

**Comment by WerWolv** [comment]
Fixed the pattern real quick. Thanks for letting me know
