### ISSUE TITLE
typo in flac.hexpat

### ISSUE THREAD

**Issue by frkami123** [WerWolv/ImHex-Patterns#119]
https://github.com/WerWolv/ImHex-Patterns/blob/11291d1ebbade0f4081841d7e7101f564ca510c0/patterns/flac.hexpat#L140-L141

typo at "mi**n**eTypeLength", should be "mimeTypeLength" instead.

error message when exvaluate flac.hexpat:
> error[E0003]: Variable error.
  --> <Source Code>:141:19
141 |     char mimeType[mineTypeLength];
                        ^
                        No variable named 'mineTypeLength' found.

**Comment by WerWolv** [comment]
Thank you! Latest commit fixes the typo
