### ISSUE TITLE
java class pattern: The code segment always displays the value of the first byte

### ISSUE THREAD

**Issue by Guigumua** [WerWolv/ImHex-Patterns#121]
![image](https://github.com/WerWolv/ImHex-Patterns/assets/43509652/47aa3f18-449e-4612-9f8a-6b0ffe36dcf6)

**Comment by paxcut** [comment]
I ran the java class pattern on out test input and I can't find any evidence of this issue.
 The pattern doesn't mention any code segments and you provide no input files that show the  error. 
 Please either provide a detailed explanation of how to reproduce the issue or some file that can be tested.

**Comment by Guigumua** [comment]
https://github.com/Guigumua/file/blob/main/Test.class

And when I use png pattern, I find that there are similar problems

![image](https://github.com/WerWolv/ImHex-Patterns/assets/43509652/2e0ea4e7-e014-4d2f-90a1-57041f092a2f)

**Comment by Guigumua** [comment]
> I ran the java class pattern on out test input and I can't find any evidence of this issue. The pattern doesn't mention any code segments and you provide no input files that show the error. Please either provide a detailed explanation of how to reproduce the issue or some file that can be tested.

in `file.methods[0].attributes[0].code[]`

**Comment by WerWolv** [comment]
Hey, sorry this is an issue in the latest release of ImHex. You can download the nightly build from https://imhex.download/#nightly which should fix the problem
