### ISSUE TITLE
[Feature] Being able to save the project from the pattern editor

### ISSUE THREAD

**Issue by LennardF1989** [WerWolv/ImHex-Patterns#149]
Because ImHex can crash if you are playing with the Pattern editor, I've made it a habit to constantly save. Currently, I have to switch to the file tab I'm working on, hit ALT+S. then switch back to the pattern editor.

Would be great if ALT+S (or CTRL+S could probably also be used there) also works from the pattern editor (or whichever tab you have focussed).

**Comment by paxcut** [comment]
this issue has already been posted in the imhex editor github as it is more approppiate there. Please only posts issues related to the patter files here. Use the pattern language github fopr problems or issues on the pattern language.

**Comment by LennardF1989** [comment]
Ah damn, I'm posting issues in the wrong repo! Thanks for the heads-up.

**Comment by paxcut** [comment]
i realize that all the different repos can be confusing so it is a normal thing to do. I also think that this way it will result in faster answers  too.
