### ISSUE TITLE
Consider supporting multiple test cases per pattern

### ISSUE THREAD

**Issue by bgilbert** [WerWolv/ImHex-Patterns#158]
Some patterns have to make decisions based on file headers, such as selecting a particular byte order or field width.  In such cases it's impossible to create a single test case that fully exercises the pattern.  Is there any reason the test suite shouldn't allow multiple test cases per pattern?

**Comment by WerWolv** [comment]
Hey, could you make an example of what you mean? I don't exactly understand your request

**Comment by bgilbert** [comment]
The CMakeLists for `tests/patterns` [selects only one test file](https://github.com/WerWolv/ImHex-Patterns/blob/b6e0557a1d06f115d9fa28e2199808f91f03ad52/tests/patterns/CMakeLists.txt#L28) for each pattern.  I'm working on improving the TIFF pattern, and there are at least two parameters (little/big endian, classic TIFF/BigTIFF) which can't be combined together into a single TIFF file.  So, for example, if there's a test case for little-endian classic TIFF, then big-endian and BigTIFF support currently can't be tested by the test suite.
