### ISSUE TITLE
Compile error [E0003] when using hex::core::get_selection()

### ISSUE THREAD

**Issue by mrehkopf** [WerWolv/ImHex-Patterns#167]
Given this minimal test case in the pattern editor:
```
#include <hex/core.pat>

hex::core::get_selection();
```
The pattern compiler outputs the following error:
```
E:   --> <Source Code>:1:417
E: 1 | #include <hex/core.pat>
E:  [421 whitespaces] ^
E:  [421 whitespaces] Variable with name 'result' already exists in this scope.
E:
E:  
```
(I removed a lot of whitespaces from the error message; at first I could not see the actual error because it was so far off to the right)

I can see that hex/core.pat uses an u128 called 'result' in the get_selection function but I don't know how to fix this :)

**Comment by mrehkopf** [comment]
...oh. Well, I should have been able to spot that. 🙈
Anyway, thanks for a swift resolution, and for such an awesome tool altogether. ImHex never ceases to amaze me.

**Comment by WerWolv** [comment]
No problem, thanks for the report too! I should have spotted this myself when I wrote it ^^
