### ISSUE TITLE
no parent avaliable 

### ISSUE THREAD

**Issue by H-H-bin** [WerWolv/ImHex-Patterns#20]
when open an elf file, and load elf.pat, there is an error:
Error at line 167: 
there no parent avaliable
![image](https://user-images.githubusercontent.com/3911177/137611981-8807ae24-f756-48ed-ac9c-59740a3b40c5.png)

**Comment by H-H-bin** [comment]
after change as below:

struct Elf {
	elf::Header header;
	program::Header program_headers[header.program_header_entry_count];
	section::Header section_headers[header.section_header_entry_count];
};

Elf elf_file @0x00;

it works.

**Comment by WerWolv** [comment]
Fixed with latest commit to ImHex
