### ISSUE TITLE
How to search pattern from start to end？

### ISSUE THREAD

**Issue by kdurant** [WerWolv/ImHex-Patterns#208]
```
struct FrameWithGPS {
    be u32 head;  // 0x01234567
    be u32 flag;
    be u32 week;
    be double second;
    be double latitude;
    be double longitude;
    be u16 reserve;
    be u16 pin_value;
};
```
 How do I find all the data in the file that matches the pattern?
I only can do `FrameWithGPS  frane @addr;`.

**Comment by EvelynTSMG** [comment]
What do you mean by "matches"? Any range of 40 bytes is a valid sequence that pattern can be applied to.

**Comment by WerWolv** [comment]
You can match for the magic value there if it's always the same. The easiest way to do that is
```cpp
struct FrameWithGPS {
    be u32 head;  // 0x01234567
    be u32 flag;
    be u32 week;
    be double second;
    be double latitude;
    be double longitude;
    be u16 reserve;
    be u16 pin_value;
};

std::mem::MagicSearch<"\x67\x45\x23\x01", FrameWithGPS> frames @ 0x00;
```

**Comment by kdurant** [comment]
![image](https://github.com/WerWolv/ImHex-Patterns/assets/2704364/0c6a1e19-dd05-4a03-92dd-4a056851cfd2)

```cpp
std::mem::MagicSearch<"\x67\x45\x23\x01", FrameWithGPS> frames @ 0x00;
```
 With this statement, I can't find anything

```cpp
std::mem::MagicSearch<"\x01\x23\x45\x67", FrameWithGPS> frames @ 0x00;
```
```
E: error[E0007]: Limit error.
E: Pattern count exceeded set limit of '131072'.
E: hint: If this is intended, try increasing the limit using '#pragma pattern_limit <new_limit>'.
I: Evaluation took 3.81501s
```

**Comment by kdurant** [comment]
> What do you mean by "matches"? Any range of 40 bytes is a valid sequence that pattern can be applied to.

Find all the frame headers, and then write the next 40 bytes of data according to the definition

**Comment by paxcut** [comment]
If your file is in little endian which is the default then the bytes in a word are read from the least significant to the most significant. For example if the data in the file reads
```cpp
\x01\x23\x45\x67
```
then you  have to read it as 
```cpp
\x67\x45\x23\x01
```
so
```cpp
std::mem::MagicSearch<"\x67\x45\x23\x01", FrameWithGPS> frames @ 0x00;
```
is correct and 
```cpp
std::mem::MagicSearch<"\x01\x23\x45\x67", FrameWithGPS> frames @ 0x00;
```
is not.
