### ISSUE TITLE
std::mem::read_string is limited in size to u8::MAX

### ISSUE THREAD

**Issue by BroGamer4256** [WerWolv/ImHex-Patterns#221]
Attempting to use a larger integer for a longer length string will silently limit the read string. To me this seems unintentional as this would mean there's no way to read strings longer than u8::MAX and the builtin function this calls has the capability of reading much more as its instead limited to size_t.

**Comment by WerWolv** [comment]
Thank you! Latest commit to the standard library fixes this.
It was a copy-paste error from std::mem::read_unsigned which takes in a u8 size too
