### ISSUE TITLE
hex::visualize isn't documented

### ISSUE THREAD

**Issue by malespiaut** [WerWolv/ImHex-Patterns#232]
Hello,

I've discovered the `hex::visualize` feature that allow to render images and 3D meshes.

Unfortunately, I can't find any documentation about this feature, and therefore struggle to use it.

An addition in the official documentation would be very welcome.

Best regards.

**Comment by paxcut** [comment]
you can find introductory documentation for visualizers [here](https://docs.werwolv.net/imhex/views/pattern-data)
