### ISSUE TITLE
Request: .rar file pattern

### ISSUE THREAD

**Issue by Devnol** [WerWolv/ImHex-Patterns#258]
I was trying to look into a rar file and noticed that no pattern existed for it, whereas zip and 7z both have pattern files. I could try to do this myself someday, I'm just putting it out here for now if someone else would like to work on it in the meantime.

This is the spec for the RAR 5 format: https://www.rarlab.com/technote.htm
And this seems to be an archive of the entire set of RAR specs? https://www.loc.gov/preservation/digital/formats/fdd/fdd000450.shtml

**Comment by targodan** [comment]
I've been looking for an excuse to dive deeper into the imhex pattern language for a while now. I think I'll take a poke at this. :)
