### ISSUE TITLE
Protobuff definition is not correct

### ISSUE THREAD

**Issue by gsi-viera** [WerWolv/ImHex-Patterns#261]
https://github.com/WerWolv/ImHex-Patterns/blob/3416d30f2b8fac4f12bf73aa1f5d5102a07b7f83/patterns/protobuf.hexpat#L34C5-L37C4

The [specification](https://protobuf.dev/programming-guides/encoding/) for protobuff states that this record is Varint Encoded. 

So it means that it's not guaranteed to have 8 bits. If the field index has its last significant bit on 1 then another byte has to be read.

I've tested this in real life payloads and I've confirmed that it's failing.

**Comment by applecuckoo** [comment]
This issue should probably be closed since it's a dupe of #152, which describes the exact same problem.
