### ISSUE TITLE
std::hash::crc32 cannot cast value to type 'pattern'

### ISSUE THREAD

**Issue by themixednuts** [WerWolv/ImHex-Patterns#273]
`string` is of type str, but I've also tried literal numbers and same error.

```
std::hash::crc32(string, 0xFFFFFFFF, 0x04C11DB7, 0xFFFFFFFF, true, true);
//                      ^ E: runtime error: Cannot cast value to type 'pattern'.fd
```

**Comment by paxcut** [comment]
I just tested the following code and it ran without problems. This was recently added so make sure you update the libraries in the content store before trying it again.
```cpp
import std.hash;

str test = "hello";
std::print("{}",std::hash::crc32(test, 0xFFFFFFFF, 0x04C11DB7, 0xFFFFFFFF, true, true));
```

**Comment by themixednuts** [comment]
> I just tested the following code and it ran without problems. This was recently added so make sure you update the libraries in the content store before trying it again.
> 
> ```c++
> import std.hash;
> 
> str test = "hello";
> std::print("{}",std::hash::crc32(test, 0xFFFFFFFF, 0x04C11DB7, 0xFFFFFFFF, true, true));
> ```

Interesting. Still have the issue, even after exiting and relaunching. 

```
import std.hash;

fn main(){
    str test = "hello";
    std::print("{}",std::hash::crc32(test, 0xFFFFFFFF, 0x04C11DB7, 0xFFFFFFFF, true, true));
};
```
```
// results

E: [ Stack Trace ]
E: C:\Users\****\AppData\Local\imhex\includes\std/hash.pat:48:94
E: 48 |  reflect_in, reflect_out);
E:                               ^
E: <Source Code>:113:86
E: 113 |  0xFFFFFFFF, true, true));
E:                               ^


E: runtime error: Cannot cast value to type 'pattern'.

```


![image](https://github.com/user-attachments/assets/6359f0b5-d185-43c2-8ff0-acaab91290ac)

**Comment by paxcut** [comment]
Does the crc32  function in the library looks like this?
```cpp
  fn crc32(ref auto pattern, u32 init, u32 poly, u32 xorout, bool reflect_in, bool reflect_out) {
        return builtin::std::hash::crc32(pattern, init, poly, xorout, reflect_in, reflect_out);
    };
 ```
 in particular, does it have the `builtin::` part added?

**Comment by themixednuts** [comment]
yea this is what the file shows

```cpp
    // C:\Users\*****\AppData\Local\imhex\includes\std\hash.pat : ln 47
    fn crc32(ref auto pattern, u32 init, u32 poly, u32 xorout, bool reflect_in, bool reflect_out) {
        return builtin::std::hash::crc32(pattern, init, poly, xorout, reflect_in, reflect_out);
    };
```

**Comment by paxcut** [comment]
You must be running an older version of Imhex, one built before the fix was added on 7/7.

**Comment by themixednuts** [comment]
That was it, off by one minor patch, thank you!

**Comment by paxcut** [comment]
yeah sorry about that. I made the assumption that the fixes were done in the library include file but seeing how yours was identical I went back and looked at the actual fix changes and noticed that .cpp files were changed which indicates imhex needs updating. A bit of running around but you got it working. Good deal! and thanks for closing the issue.
