### ISSUE TITLE
Question about intended repository contents & contribution guidelines

### ISSUE THREAD

**Issue by Frain-Breeze** [WerWolv/ImHex-Patterns#3]
Is this repository for common filetypes only, or are very specific, rarely-used formats also welcome?
I have quite a few of these specific formats, most of them archive, texture and model filetypes. Ones which aren’t (publicly) documented elsewhere.

Aside from that, what are the contribution guidelines? Are incomplete patterns allowed? For formats which aren’t fully understood yet.

**Comment by WerWolv** [comment]
Hi!
You're more than welcome to submit any pattern file that you think might be useful for others. As long as it's not a pattern for some internal file type that's only useful to you, everything goes really, as well as incomplete ones. They still provide helpful information for other people working with those formats
