### ISSUE TITLE
how to add additional information to structs

### ISSUE THREAD

**Issue by eybisi** [WerWolv/ImHex-Patterns#36]
I'm writing pattern for dex file and here is my pattern
```
#pragma pattern_limit 0x20000
namespace dex {

	struct Header {
		char magic[4];
		char version[4];
		u32 checksum;
		char signature[20];
		u32 fileSize;
		u32 headerSize;
		u32 endianTag;
		u32 linkSize;
		u32 linkOff;
		u32 mapOff;
		u32 stringIdsSize;
		u32 stringIdsOffset;
		u32 typeIdsSize;
		u32 typeIdsOffset;
		u32 protoIdsSize;
		u32 protoIdsOffset;	
		u32 fieldIdsSize;
		u32 fieldIdsOffset;
		u32 methodIdsSize;
		u32 methodIdsOffset;
		u32 classDefSize;
		u32 classDefOffset;
		u32 dataSize;
		u32 dataOffset;
	};

	struct StringDataItem {
		u8 size;
		char string[size];
	
	};

	struct StringIdItem {
		u32 stringDataOffset;
	};
	
	struct MethodIdItem {
		u16 classIdx;
		u16 protoIdx;
		u32 nameIdx;
	
	};
	struct ClassDefItem {
		u32 classIdx;
		u32 accessFlags;
		u32 superClassIdx;
		u32 interfacesOffset;
		u32 sourceFileIdx;
		u32 annotationsOffset;
		u32 classDataOffset;
		u32 staticValuesOffset;
	
	};
	
	struct TypeIdItem {
		u32 descriptorIdx;
		
	};
	struct ProtoIdItem {
		u32 shortyIdx;
		u32 returnTypeIdx;
		u32 parametersOffset;
		
	};
	
	struct FieldIdItem {
		u16 classIdx;
		u16 typeIdx;
		u16 nameIdx;
		
	};
	
	struct MapList {
		u32 size;
	};
	

}

dex::Header header @0x0;
dex::StringIdItem stringIds[header.stringIdsSize] @ header.stringIdsOffset;
dex::MethodIdItem methodIds[header.methodIdsSize] @ header.methodIdsOffset;
dex::ClassDefItem classDefs[header.classDefSize] @ header.classDefOffset;
dex::MapList mapList @ header.mapOff;
dex::TypeIdItem typeIds[header.typeIdsSize] @ header.typeIdsOffset;
dex::ProtoIdItem protoIds[header.protoIdsSize] @ header.protoIdsOffset;
dex::FieldIdItem fieldIds[header.fieldIdsSize] @ header.fieldIdsOffset;
```

If you look at StringIdItem struct in dex namespace, normally it will point to StringDataItem. StringDataItem is not in StringIdItem struct. Instead its in where StringIdItem.stringDataOffset points to. So I would like to find each StringDataItem and get string from there and write this information to pattern data or somewhere so user can see. 

In kaitai there can be two field in definition `seq` and `instances` my question is there a way to show information like instances in imhex patterns.

**Comment by eybisi** [comment]
Second approach works! How can I give current position as pointer ? `StringDataItem *stringDataItem : u32` will need a @ operator right ?

**Comment by WerWolv** [comment]
Simply 
```rust
struct StringIdItem {
    StringDataItem *stringData : u32;
};
```
should work. That places a pointer at that location which is 4 bytes large and places a StringDataItem at the location determined by the value at the pointer location

**Comment by WerWolv** [comment]
Seems to work fine for me. Are you using the latest version of ImHex?

**Comment by WerWolv** [comment]
Great :)

**Comment by eybisi** [comment]
Is that okay that parsed string is not colored in hex editor ? 
![2022-04-27_18-15](https://user-images.githubusercontent.com/21275072/165552747-20d170d9-0dba-42f9-ab5a-34246ea6b4b2.png)

**Comment by WerWolv** [comment]
That does look like a bug, I'll see if I can fix it
