### ISSUE TITLE
Integration with Kaitai Struct

### ISSUE THREAD

**Issue by X-C3LL** [WerWolv/ImHex-Patterns#4]
Hi!

I love your project (ImHex) but I believe it can be more powerful if it uses something like Kaitai Struct (https://kaitai.io/) for describing the binary data structures. Using .ksy files for importation/exportation can be a huge improvement because those files can be turned inmediatly to parsers in any language supported by Kaitai (C, python, JavaScript, Go, etc..). Also there is a big community describing file formats in this declarative language, so you can take advantage of it.

Best regards!

**Comment by WerWolv** [comment]
I already had that discussion over in the ImHex issues and I'd really rather develop this myself instead of just using something existing.

**Comment by seanf** [comment]
> I already had that discussion over in the ImHex issues and I'd really rather develop this myself instead of just using something existing.

Probably this discussion: https://github.com/WerWolv/ImHex/issues/61
