### ISSUE TITLE
jpeg pattern error with embedded thumbnail

### ISSUE THREAD

**Issue by ocococococ** [WerWolv/ImHex-Patterns#82]
Hi,
It seems there is an error when using jpeg pattern (jpeg.hexpat) regarding embedded thumbnail (with MacOs 1.26.2 version):

`error[P0002]: Unexpected expression
  --> <Source Code>:63:71
63 |     Pixel thumbnail[thumbnailX * thumbnailY] [[sealed, hex::visualize("bitmap", thumbnailX, thumbnailY)]];
                                                                           ^
                                                                           Expected ')', got Separator (,)
`

Removing this part
**[[sealed, hex::visualize("bitmap", thumbnailX, thumbnailY)]]** 
sure solves the problem but obviously also prevents intended thumbnail visualisation feature.

May be, I'm wrong but it seems hex::visualize function is not 'seen' by jpeg.hexpat.

**Comment by WerWolv** [comment]
Hey
I should probably not have committed this already. This is part of a new feature I introduced a few commits ago and is not yet supported in the latest release. I'll remove it again for now from the pattern, thanks for letting me know.
