### ISSUE TITLE
[Feature] Add Zlib Pattern

### ISSUE THREAD

**Issue by amelkikh** [WerWolv/ImHex-Patterns#85]
Hi!

Please help to implement Zlib pattern.
Trying to figure out how to realize this but no knowledge in c++.
FYI: I'm reversing in python using that package https://github.com/python/cpython/blob/main/Modules/zlibmodule.c

Best regards.

**Comment by WerWolv** [comment]
Implementing a basic zlib pattern probably won't be super difficult. You can find the specs here: https://www.rfc-editor.org/rfc/rfc1950
Decompressing the data within the pattern language however will take a lot more work.
